[build]
builder = "nixpacks"
buildCommand = "npm run install:all && npm run build && cd server && npx prisma generate"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
